### PR TITLE
mathjax - fix use of CDN and allow for fail-over if there is no connectivity

### LINKED ISSUE #8078: mathjax CDN has been retired; need to migrate to another CDN and must use https to prevent mixed-mode blocking errors
Currently, when rendering a site with MathML on https, the current use of the mathjax CDN has a number of problems.
1. Does not load because of [mixed-mode blocking](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content) as seen here: https://wet-boew.github.io/wet-boew/demos/mathml/mathml-en.html . The offending line is here: https://github.com/wet-boew/wet-boew/blob/master/src/core/wb.js#L531 :
`

					Modernizr.load( {
						load: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=Accessible",
						complete: function() {

							// Identify that initialization has completed
							wb.ready( $document, componentName );
						}
					} );`
2. points to an http version
Further, console says: "WARNING: cdn.mathjax.org has been retired. Check https://www.mathjax.org/cdn-shutting-down/ for migration tips."
3. The "accessible" configuration is deprecated as seen here: http://docs.mathjax.org/en/latest/config-files.html#the-accessible-configuration-file-deprecated
4. Latest.js is used instead of a specific version (which is not recommended anymore) as per notes here: https://www.mathjax.org/cdn-shutting-down/

Suggested resolution: switch to a different CDN such as https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js or something else agreed upon by wet-boew maintainers. In principle, I'd prefer http://www.jsdelivr.com/ but I have an [outstanding](https://jsdelivr.uservoice.com/forums/164147-plugins-submission/suggestions/19875577-mathjax-had-have-the-versions-load-properly-throug) [support requests that needs to be resolved](https://jsdelivr.uservoice.com/forums/164147-plugins-submission/suggestions/2967289-mathjax-http-www-mathjax-org) before we can go with it.

### PR DESCRIPTION
**Pull request by nathanv**
This would close #8078 if accepted.

### CODE REVIEW

File: Gruntfile.coffee [hunk 1]
```diff
@@ -309,6 +310,7 @@ module.exports = (grunt) ->
 		themeDist: "dist/theme-wet-boew"
 		jqueryVersion: @file.readJSON "lib/jquery/bower.json"
 		jqueryOldIEVersion: @file.readJSON "lib/jquery-oldIE/bower.json"
+		MathJaxVersion: @file.readJSON "lib/MathJax/.bower.json"
```
Comment (nschonni) [inline Gruntfile.coffee]: Not sure there is a leading `.` on the `bower.json`

File: Gruntfile.coffee [hunk 2]
```diff
@@ -39,6 +39,7 @@ module.exports = (grunt) ->
 			"sprites"
 			"css"
 			"js"
+			"string-replace"
```
Comment (nschonni) [inline Gruntfile.coffee]: maybe add a particular target so it's clearer what is being replaced. EX: `string-replace:MathJaxVersion`

File: Gruntfile.coffee [hunk 3]
```diff
@@ -1329,6 +1345,15 @@ module.exports = (grunt) ->
 				options:
 					testname: "Local Test - <%= grunt.template.today('yyyy-mm-dd hh:MM') %>"
 
+		"string-replace":
+			inline:
+				files:
+					'dist/wet-boew/js/': 'dist/wet-boew/js/*.js'
+				options:
+					replacements: [
```
Comment (nschonni) [inline Gruntfile.coffee]: I noticed there is a few query string params on the CDN, should those get exposed here too?

**Review by nschonni — COMMENTED** [review]
Think this makes sense, but it might be better to use NPM because of #8063

File: Gruntfile.coffee (hunk 2 above)
Comment (nathanv) [inline Gruntfile.coffee]: Great idea. I'll fix that.

File: Gruntfile.coffee (hunk 1 above)
Comment (nathanv) [inline Gruntfile.coffee]: Amazingly there is...

File: Gruntfile.coffee (hunk 3 above)
Comment (nathanv) [inline Gruntfile.coffee]: Hmm good question. That would be important if the default parameters are changed over time as they have been. Good idea. I'll make that fix.

File: Gruntfile.coffee (hunk 2 above)
Comment (nathanv) [inline Gruntfile.coffee]: @nschonni so turns out that string-replace doesn't have multi-task support so I'm going to try to use https://github.com/yoniholmes/grunt-text-replace instead. I've been juggling a few things but I'll try to finish it up asap.

Comment (nschonni) [inline Gruntfile.coffee]: Maybe better to stick with `string-replace` even if we can't add the target. Looking at the project it looks like it was more recently maintained and updated for Grunt 1.0 where the other wasn't

File: Gruntfile.coffee (hunk 3 above)
Comment (lucas-hay) [inline Gruntfile.coffee]: @nathanv we are scheduled to release WET next Tuesday (August 15th), any chance this PR will be updated/ready by then?

**Comment by lucas-hay** [comment]
@nathanv any news?

File: Gruntfile.coffee (hunk 3 above)
Comment (nathanv) [inline Gruntfile.coffee]: Hello @lucas-hay . We found a quick workaround internally to get the issue sorted and I had to move onto other stuff. I am working on it right now to get it to a better point hopefully good enough to ship.

File: Gruntfile.coffee (hunk 2 above)
Comment (nathanv) [inline Gruntfile.coffee]: @nschonni okay let's stick with it then

File: Gruntfile.coffee (hunk 3 above)
Comment (lucas-hay) [inline Gruntfile.coffee]: Thanks @nathanv 
Reply here if you get this ready before tomorrow and we can look at merging it.

File: site/includes/footerresources.hbs [hunk 4]
```diff
@@ -1,5 +1,6 @@
 <!--[if gte IE 9 | !IE ]><!-->
 <script src="{{#if offline}}{{assets}}/../wet-boew/js{{else}}https://ajax.googleapis.com/ajax/libs{{/if}}/jquery/{{environment.jqueryVersion}}/jquery.js"></script>
+<script>window.jQuery || document.write('<script src="{{assets}}/../wet-boew/js/jquery/{{environment.jqueryVersion}}/jquery.js"><\/script>');</script>
```
Comment (nschonni) [inline site/includes/footerresources.hbs]: Think the previous line covers this off

File: Gruntfile.coffee [hunk 5]
```diff
@@ -1329,6 +1348,15 @@ module.exports = (grunt) ->
 				options:
 					testname: "Local Test - <%= grunt.template.today('yyyy-mm-dd hh:MM') %>"
 
+		"string-replace":
+			inline:
+				files:
+					'dist/wet-boew/js/': 'dist/wet-boew/js/*.js'
```
Comment (nschonni) [inline Gruntfile.coffee]: Could target the `concat.core.dest` and `concat.coreIE8.dest` values to glob through less files.

**Review by nathanv — COMMENTED** [review]
Ready for final review.

File: Gruntfile.coffee (hunk 3 above)
Comment (nathanv) [inline Gruntfile.coffee]: Ready for final review.

File: site/includes/footerresources.hbs (hunk 4 above)
Comment (lucas-hay) [inline site/includes/footerresources.hbs]: @nschonni are you ok with this now?
I will be starting the release at 9:00 and wondering if this should be merged?
@LaurentGoderre @duboisp any comments?

Comment (LaurentGoderre) [inline site/includes/footerresources.hbs]: Yeah this line is not very usefull

**Comment by nathanv** [comment]
Without that line, I wasn't able to get Jquery to load in an intranet
environment.

File: site/includes/footerresources.hbs (hunk 4 above)
Comment (nathanv) [inline site/includes/footerresources.hbs]: Without the line I wasn't able to get Jquery to load when blocking Google's Jquery url using Chrome.

**Comment by LaurentGoderre** [comment]
@nathanv these files are autogenerated from a site builder. There is an option for local build to not use the CDN and use a local copy. You may use your line in your own setup or change the paths to local versions but it shouldn't be included in WET.

File: site/includes/footerresources.hbs (hunk 4 above)
Comment (nathanv) [inline site/includes/footerresources.hbs]: Had a quick offline discussion with @laurentgoderre. I will remove the line when I have access to my laptop. Currently out of the office unexpectedly but I'll be able to get something sorted before end of business day.

**Comment by nathanv** [comment]
I removed the one line as was requested by @LaurentGoderre

File: Gruntfile.coffee (hunk 3 above)
Comment (nathanv) [inline Gruntfile.coffee]: @lucas-hay I removed the line as requested by @LaurentGoderre :) so ready for final-final review.

**Comment by nathanv** [comment]
@lucas-hay anything I can do to get this in the next release?

**Comment by lucas-hay** [comment]
@nathanv as long as @LaurentGoderre and @nschonni approve the updates you made as they requested, I will merge it as soon as they approve.

File: Gruntfile.coffee (hunk 5 above)
Comment (nathanv) [reply Gruntfile.coffee]: @nschonni is this the last thing I need to resolve?

File: site/includes/footerresources.hbs (hunk 4 above)
[the remark this answers is not in the document]
Comment (nathanv) [reply site/includes/footerresources.hbs]: @LaurentGoderre I removed the offending line here... is there anything else needed?

**Comment by lucas-hay** [comment]
@LaurentGoderre @nschonni 
Do you guys approved now that the changes you had requested are implemented?

File: src/core/wb.js [hunk 6]
```diff
@@ -561,17 +569,18 @@ Modernizr.load( [
...
+					Modernizr.load( [ {
+						load: "timeout=500!https://cdn.jsdelivr.net/npm/mathjax@BOWER_VERSION_MATHJAX/MathJax.js?config=Accessible",
 						complete: function() {
+							Modernizr.load( [ {
+								test: window.MathJax === undefined,
+								yep: "mthjx!MathJax.js?config=Accessible"
+							} ] );
 
 							// Identify that initialization has completed
 							wb.ready( $document, componentName );
```
Comment (LaurentGoderre) [inline src/core/wb.js]: This is still a potential race condition since you are not calling this line from the backup

**Review by LaurentGoderre — DISMISSED** [review]

File: src/core/wb.js (hunk 6 above)
Comment (lucas-hay) [reply src/core/wb.js]: @nathanv Any news on Laurent's review?

Comment (duboisp) [reply src/core/wb.js]: @nathanv To avoid the race condition you can run a test with ```testReady``` like:
```js
Modernizr.load( {
	load: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=Accessible",
	testReady: function() {
		return ( window.MathJax && window.MathJax.isReady );
	},
	complete: function() {

		// Identify that initialization has completed
		wb.ready( $document, componentName );
	}
} );
```
 https://github.com/wet-boew/wet-boew/blob/master/src/core/wb.js#L566

**Comment by nathanv** [comment]
Thanks for the feedback. I will fix it this weekend. :).

**Comment by lucas-hay** [comment]
Please let us know when fixed so we can merge ASAP so this can be included
in the 4.0.27 release on November 30th.

File: Gruntfile.coffee [hunk 7]
```diff
@@ -1061,6 +1063,20 @@ module.exports = (grunt) ->
 						return dest + "/" + src.replace ".debug", ""
 					expand: true
 					flatten: true
+				,
+					cwd: "lib/MathJax"
+					src: [
+						"MathJax.js"
+						"config/**"
+						"docs/**"
```
Comment (Empereol) [inline Gruntfile.coffee]: Should the docs be included? When `bootlint` gets run from the `Gruntfile.coffee`, it fails on the HTML files copied over into this directory. I suspect these files aren't even required and could be removed to easily resolve this issue.

Comment (duboisp) [reply Gruntfile.coffee]: @Empereol Please submit a [new issue](https://github.com/wet-boew/wet-boew/issues/new) with your concern. That way it is easier to track and ensure that you will get a follow up.

Comment (Empereol) [reply Gruntfile.coffee]: Can do. Issue #8250
