### PR TITLE
Plugin Tables: Do not create sort/order button when column sort is di…

### LINKED ISSUE #9588: [BUG] Tables - removing sorting from a column generates aria-controls="undefined"
## Required information

**Describe the bug**
We use a table with 1 column that will not be orderable.  Upon rendering, the header contains a button
button type="button" aria-controls="undefined" title="activate for ascending sort"

The aria-controls generate a W3C validation error:
Error: The aria-controls attribute must point to an element in the same document.

Here is the table definition
```
<table  id="ResultsTable" class="cards wb-tables table draftLayout"
                   data-wb-tables='{"paging":"true", "ordering":"true", "info":"true", "columnDefs": [ {"orderable": false, "targets": [5]}], "aaSorting": [[2, "asc"]], "lengthMenu": [[9, 18, 36, 54, -1], [9, 18, 36, 54, "@Common.AllFilter"]]}'>
```

**Expected behaviour**
No button at all as the sorting is not available

**Who shall do the work?**
I am asking for Principal publisher to please do the work

## Additional information (optional)

**Version of WET-BOEW/GCWeb you are using**
v4.0.47

### PR DESCRIPTION
**Pull request by wewhite**
…sabled.

There are multiple ways to disable column sorting. This patch does not allow button to be created if th column class sorting_disabled is present.

Related to #9476
Fixes #9588

## What does this pull request (PR) do? / Que fait cette demande « pull » (PR)?
Column sorting can be enabled/disabled different ways:
- using th data-orderable attribute
- using columns in data-wb-table settings
- using columnDefs in data-wb-table settings

When using data-wb-table settings:
```
"columns": [
    { "orderable": false },
    null,
    null,
    null,
    null
  ]  }'
```
or 

```
"columnDefs": [ {
"targets": 0,
"orderable": false
} ]
```

The class name `sorting_disabled` is added to the table header, and WET tables still adds the button code to it.
Adding another check in the if statement, does not add the button code if `sorting_disabled` class exists.

### CODE REVIEW

File: src/plugins/tables/tables.js [hunk 1]
```diff
@@ -226,7 +226,7 @@ $document.on( "init.dt", function( event ) {
 		$elm.find( "th" ).each( function() {
 			var $th = $( this ),
 				label = ( $th.attr( "aria-sort" ) === "ascending" ) ? i18nText.aria.sortDescending : i18nText.aria.sortAscending;
-			if ( $th.attr( "data-orderable" ) !== "false" ) {
+			if ( ( $th.attr( "data-orderable" ) !== "false" ) && !( $th.hasClass( "sorting_disabled" ) ) ) {
```
Comment (polmih) [inline src/plugins/tables/tables.js:229]: Question: what is the purpose of manually adding the class "`sorting_disable`" in the table head? Is it to disable the column sorting? Why we should add it since sorting functionality and the visual button is handled well by the attribute `data-orderable`?
Thank you

Comment (wewhite) [reply src/plugins/tables/tables.js:229]: DataTables adds the class `sorting_disable` automatically, it is not manually added.

Disable column sorting using DataTables API example:
`data-wb-tables='{ "ordering" : false }'>`

There are multiple ways to disable sorting/ordering with DataTables.

If only use the DataTables API config, and not using `data-orderable` in the `<th...`, the buttons get added, with `aria-controls=undefined` and shows the buttons.

**Review by polmih — APPROVED** [review]
locally tested. No issues found
