### PR TITLE
Core: Ensure getUrlParts() always returns slash-prefixed pathnames.

### LINKED ISSUE #8109: Multimedia player: IE 10-11 and older versions of Edge can't playback youtu.be videos.
The extra logic #7835 added to support short YouTube URLs assumes that the pathname property will always consist of a string that begins with a forward slash (/). If a long YouTube URL isn't used, it attempts to treat the URL as a youtu.be one. A valid youtu.be URL's pathname is presumed to always be formatted as "/ID". The extra logic was designed to always strip out the first character, then treat the result as a potential video ID.

It turns out that the extra logic doesn't work properly in any versions of Internet Explorer, nor early versions of Edge. Due to a [browser bug](https://connect.microsoft.com/IE/feedbackdetail/view/1002846/pathname-incorrect-for-out-of-document-elements), pathname's opening slash character is always omitted on generated ``a`` elements. This is currently resulting in the first character of all youtu.be video IDs getting stripped out prior to being retrieved from YouTube.

The end result is that the multimedia player plugin is currently incapable of playing back any youtu.be videos in the aforementioned browsers, since it's requesting invalid video IDs from YouTube.

I'll send a PR very soon to fix it. This issue only exists to give extra context to what my forthcoming PR is trying to resolve.

### PR DESCRIPTION
**Pull request by EricDunsworth**
According to the W3C's HTML specification (https://w3c.github.io/html/browsers.html#dom-location-pathname), the pathname attribute must always start with a forward slash character. Virtually every browser does this. But due to a browser bug (https://connect.microsoft.com/IE/feedbackdetail/view/1002846/pathname-incorrect-for-out-of-document-elements), all versions of Internet Explorer and early versions of Edge omit the forward slash from pathnames retrieved from generated a elements that weren't added to the body.

Since getUrlParts() works by generating an a element that never gets added to the body, any pathname attributes returned by it are affected.

This commit fixes it by inserting a forward slash at the beginning of any pathnames that lack one. It borrows a regex from the NavCurrent plugin that's already in use for the same purpose.

Fixes #8109 and doesn't interfere with the tabbed interface plugin (i.e. the only other WET/GCWeb plugin that uses pathnames extracted from getUrlParts()).

### CODE REVIEW

File: src/core/wb.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ var getUrlParts = function( url ) {
 			host: a.host,
 			hostname: a.hostname,
 			port: a.port,
-			pathname: a.pathname,
+			pathname: a.pathname.replace( /^([^\/])/, "/$1" ),
```
Comment (duboisp) [inline src/core/wb.js]: Just add a comment that specify this fix is for IE and Edge specific

**Review by duboisp — CHANGES_REQUESTED** [review]

**Comment by EricDunsworth** [comment]
@duboisp I've added a (sorta long) line comment with a basic overview of what replace() is doing and a reference to this PR.

**Review by duboisp — APPROVED** [review]
