### PR TITLE
Lightbox: Fixed positioning of close button for AJAX sources

### LINKED ISSUE #6600: AJAX Ligtbox close button Problem
I found a small bug in the modal lightbox.  I could only find this in the one instance of this plugin but the close button ends up moving the right side of the screen.  You can actually see it on the demo page:  http://wet-boew.github.io/v4.0-ci/demos/lightbox/lightbox-en.html

I was looking at the Ajax Example 1.

modallightboxerror

Any thoughts on the fix?

### PR DESCRIPTION
**Pull request by pjackson28**
Fixes #6600

### CODE REVIEW

File: src/plugins/lightbox/lightbox.js [hunk 1]
```diff
@@ -210,19 +210,22 @@ var componentName = "wb-lbx",
...
+					} else {
+						$response = $( mfpResponse.data );
 					}
 
 					$response
 						.find( ".modal-title, h1" )
-						.first()
-						.attr( "id", "lbx-title" );
+							.first()
+								.attr( "id", "lbx-title" );
```
Comment (LaurentGoderre) [inline src/plugins/lightbox/lightbox.js]: Not sure this indendation change is necessary in the future.
